INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_0wgmejdyn', 'General', 'What is BLINTZY?', 'BLINTZY is a campus-focused service platform designed to make student and campus-related services more convenient, organized, and accessible through a single digital platform.', 1, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_h7ft62kci', 'General', 'Who can use BLINTZY?', 'BLINTZY is primarily designed for students and authorized campus users. Access to specific services may depend on the campus, service availability, and account eligibility.', 2, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_izlwg22a6', 'General', 'Which location does BLINTZY currently serve?', 'BLINTZY currently focuses on campus services associated with Ramachandra College of Engineering, Eluru, Andhra Pradesh. Service availability may change based on operational coverage.', 3, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_r54jc8mjv', 'Account and Login', 'How do I create a BLINTZY account?', 'Select the Sign Up or Create Account option, enter the required details, and complete the onboarding process.', 4, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_o1a6zsa62', 'Account and Login', 'What happens if my email is already registered?', 'If the email is already associated with an account, BLINTZY will display: This email is already registered. Please log in or use "Forgot Password" if you cannot access your account. You can then go to Login or use Forgot Password.', 5, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_v5igotuma', 'Account and Login', 'I forgot my password. What should I do?', 'Open the Forgot Password option, enter your registered email address, and request a password-reset link. Check your inbox and spam/junk folder. Open the link and create a new password.', 6, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_hw7e9cmzf', 'Printing Services', 'What services are available through BLINTZY?', 'Depending on current availability, BLINTZY may support: PDF printing, Black-and-white printing, Colour printing, Single-sided printing, Double-sided printing, Photocopying, Spiral binding, Manual printing, Custom document uploads, Pickup and/or delivery services.', 7, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_qtx0j39ys', 'Printing Services', 'What file formats can I upload?', 'PDF files are supported for document printing. If additional formats are supported in the future, they should be displayed dynamically from the service configuration.', 8, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_g4rlgo0m8', 'Printing Services', 'Can I upload my own document?', 'Yes, users may upload supported documents for printing, subject to file-size, file-type, content, and service restrictions.', 9, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_xz7wnvle9', 'Orders and Payments', 'How can I place a printing order?', 'Select a service, upload or choose the required document, configure printing preferences, review the order details, and complete payment if required.', 10, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_nrdl5w6ui', 'Orders and Payments', 'How can I check my order status?', 'Open the Orders section to view the current status, order details, payment status, and available pickup or delivery information.', 11, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_xfzlugp3g', 'Pickup and Delivery', 'What are BLINTZY’s service timings?', 'BLINTZY’s printing, pickup, delivery, and order-processing timings may vary depending on operational availability. The latest timings must be controlled and displayed through the admin panel.', 12, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_s4o35o38p', 'Uploaded Files', 'Are my uploaded files private?', 'Uploaded files should be used only for the requested service and order fulfillment. Access must be limited to the user and authorized BLINTZY administrators or assigned service providers who require access to complete the order.', 13, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_l3dn59mmq', 'Cancellation and Refunds', 'Can I cancel my order?', 'Cancellation depends on the order status and whether printing, binding, delivery, or processing has already started. The application should display the applicable cancellation rules.', 14, 'active', 1789373212535, 1789373212535);
INSERT INTO faqs (id, category, question, answer, display_order, status, created_at, updated_at) VALUES ('faq_vrpu5kblw', 'Support', 'How can I contact BLINTZY Support?', 'Users can contact BLINTZY through: Email: theblintzy@gmail.com', 15, 'active', 1789373212535, 1789373212535);

INSERT INTO platform_settings (setting_key, setting_value, updated_at) VALUES ('support_email', 'theblintzy@gmail.com', 1789373212535) ON CONFLICT(setting_key) DO UPDATE SET setting_value = excluded.setting_value, updated_at = excluded.updated_at;
INSERT INTO platform_settings (setting_key, setting_value, updated_at) VALUES ('app_version', 'APP VERSION V1.0.0', 1789373212535) ON CONFLICT(setting_key) DO UPDATE SET setting_value = excluded.setting_value, updated_at = excluded.updated_at;
